auth_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^authorize/', views.authorize_view, name='authorize'),
    url(r'^registration/', views.registration_view, name='registration'),
]

django_start/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('message.urls', namespace="message")),
    url(r'^auth_app/', include('auth_app.urls', namespace="auth_app")),
]

message/urls.py
from django.conf.urls import url

from message.views import MessageCreate
from . import views

urlpatterns = [
    url(r'^$', MessageCreate.as_view(), name='message'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^message/', MessageCreate.as_view(), name='message'),

]

auth_app/models.py
from django.db import models

# Create your models here.

message/models.py
from __future__ import unicode_literals

from django.core.mail import EmailMessage
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):

    SENT = 1
    NOT_SENT = 2

    AVAILABLE_CHOICES = (
        (SENT, 'Отправлено'),
        (NOT_SENT, 'Не отправлено')
    )

    recipient_email = models.EmailField(default='')
    text = models.TextField(blank=True)
    title_text = models.CharField(max_length=100, blank=True)
    parent_username = models.ForeignKey('auth.User')

    created = models.DateTimeField(default=timezone.now)
    status = models.SmallIntegerField(verbose_name='статус отправки сообщения', choices=AVAILABLE_CHOICES)

auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserAuthForm(forms.Form):
    username = forms.CharField(label='Username', max_length=150)
    password = forms.CharField(widget=forms.PasswordInput, label='Password')


class UserCreationCustomForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

message/forms.py
from django import forms

from .models import *


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title_text', 'text', 'recipient_email']

auth_app/views.py
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse, QueryDict
from django.shortcuts import render
from django.urls import reverse

from django.views.decorators.csrf import csrf_protect

from auth_app.forms import UserAuthForm, UserCreationCustomForm


@csrf_protect
def registration_view(request):
    """ Регистрирует и авторизирует """
    if request.method == "POST":
        user_creation_form = UserCreationCustomForm(QueryDict(request.POST.get('form')))
        if user_creation_form.is_valid():
            user_creation_form.save()
            new_user = auth.authenticate(username=user_creation_form.cleaned_data['username'],
                                         password=user_creation_form.cleaned_data['password2'])
            auth.login(request, new_user)
            return JsonResponse({'success': True, 'url_redirect': reverse('message:message')})
        else:
            return JsonResponse(
                {'success': False, 'errors': 'Проверьте форму на правильность заполнения или логин занят'})
    return render(request, 'auth_app/registration.html', {'form': UserCreationCustomForm()})


@csrf_protect
def authorize_view(request):
    """ Авторизация пользователя """
    if request.method == 'POST':
        auth_form = UserAuthForm(QueryDict(request.POST.get('form')))
        if auth_form.is_valid():
            user = auth.authenticate(username=auth_form.cleaned_data['username'],
                                     password=auth_form.cleaned_data['password'])
            if user is not None:
                auth.login(request, user)
                return JsonResponse({'success': True, 'url_redirect': reverse('message:message')})
            else:
                return JsonResponse({'success': False, 'errors': 'Не верный  логин или пароль'})

    return render(request, 'auth_app/authorize.html', {'form': UserAuthForm()})

message/views.py
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.views import generic

from message.forms import MessageForm
from message.models import Message


def logout(request):
    auth.logout(request)
    return redirect('auth_app:authorize')


class MessageCreate(LoginRequiredMixin, generic.CreateView):
    """ Отображает форму отправки, сохраняет сообщение в базу отправляет сообщение """
    form_class = MessageForm
    template_name = 'message/message.html'
    success_url = '/message/'

    def dispatch(self, request, *args, **kwargs):
        """ Допишет в self текущего пользователя """
        self.user = User.objects.get(username=request.user)
        return super(MessageCreate, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """ Заполнит недостающие поля, и отправит сообщение на эл. почту """
        message = form.save(commit=False)
        message.parent_username = self.user
        mail = EmailMessage(message.title_text, message.text, self.user.email,
                            [message.recipient_email])
        if mail.send(fail_silently=False):
            message.status = Message.SENT
        else:
            message.status = Message.NOT_SENT
        message.save()
        return super(MessageCreate, self).form_valid(form)

auth_app/templates/auth_app/authorize.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block login %}
 <div class="general-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <form action="{% url 'auth_app:authorize' %}" id="authorize" method="post">
                        {% csrf_token %}
                        {{ form }}

                    <div >
                        <button class="btn btn-secondary " type="submit" >log ip</button>
                         <a href="{% url 'auth_app:registration' %}" class="btn btn-secondary " >log up</a>
                    </div>

                    <div id="error"></div>
                    </form>


                </div>
            </div>
        </div>
</div>
    <script type="text/javascript" src="{% static 'auth_app/authorize_registration_ajax.js' %}"></script>
{% endblock %}

auth_app/templates/auth_app/registration.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block registration %}
     <div class="general-container">
            <div class="container top-container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2" id="test">
                        <form action="{% url 'auth_app:registration' %}" id="registration" method="post" >
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button class="btn btn-secondary " type="submit" >Зарегистрироваться</button>
                        </form>
                        <div id="error"></div>
                    </div>
                </div>
            </div>
    </div>
<script type="text/javascript" src="{% static 'auth_app/authorize_registration_ajax.js' %}"></script>

{% endblock %}

authorize_registration/templates/authorize_registration/login.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block login %}
 <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <form action="{% url 'authorize_registration:authorize' %}" id="login" method="post">
                        {% csrf_token %}

                        <label for="username">Username</label>
                        <input type="text" name="username" id="username">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password">

                    <div >
                        <button class="btn btn-secondary " type="submit" >log ip</button>
                         <a href="{% url 'authorize_registration:registration' %}" class="btn btn-secondary " >log up</a>
                    </div>

                    <div id="error"></div>
                    </form>


                </div>
            </div>
        </div>
</div>
    <script type="text/javascript" src="{% static 'authorize_registration/authorize_registration_ajax.js' %}"></script>
{% endblock %}

authorize_registration/templates/authorize_registration/registration.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block registration %}
     <div class="general-container">
            <div class="container top-container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2" id="test">
                        <form action="{% url 'authorize_registration:registration' %}" id="registration" method="post" >
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-secondary " type="submit" >Зарегистрироваться</button>
                        </form>
                        <div id="error"></div>
                    </div>
                </div>
            </div>
    </div>
<script type="text/javascript" src="{% static 'authorize_registration/authorize_registration_ajax.js' %}"></script>

{% endblock %}

message/templates/message/message.html
{% extends 'main.html' %}
{% block message %}

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <form action="{% url 'message:logout' %}" method="post" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <button class="btn" type="submit">log out</button>
    </form>

</nav>

<div class="general-container">
    <div class="container top-container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <form action="{% url  'message:message'  %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}



                    <button type="submit" class="btn btn-secondary">Отправить</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/main.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous">

    </script>
</head>
<body>
<script>

</script>
<div id="content">

    {% block message %}{% endblock %}
    {% block login %}{% endblock %}
    {% block registration %}{% endblock %}
</div>


</body>
</html>